-- BEGIN TRAN ELE FUNCIONA COMO UM RESPAWN
BEGIN TRAN

SELECT * FROM Canal

DELETE FROM Canal WHERE CanalID > 0 

-- O COMMIT SALVA ESSE NOSSO RESPAWN
COMMIT

-- O ROLLBACK VOLTA PARA O NOSSO PONTO INICIAL (ELE VOLTA NO COMMIT CASO ELE TENHA SIDO EXECUTADO ANTES)
ROLLBACK

