-- FUNÇÃO DE TEMPO 

-- DIFERENÇA ENTRE DATE E DATETIME 

-- FUNÇÃO GETDATE PEGA A DATA E HORA ATUAL DO SERVIDOR
SELECT GETDATE() 

-- CAST FORÇA A CONVERSÃO
SELECT CAST(GETDATE() AS DATE);
SELECT CAST(GETDATE() AS VARCHAR);
SELECT CAST(GETDATE() AS INT);

--DATEDIFF 
-- DIFERENÇA ENTRE DUAS DATAS 
-- A DIFERENÇA PODE SER VISTA POR YEAR || MONTH || DAY
SELECT DATEDIFF(YEAR, '2003-09-30', GETDATE()); 

--DATEADD()
-- ELE ADICIONA UMA FORMA DE CONSULTA COM OUTROS DIAS DA DATA
-- ADICIONAR OU SUBTRAIR DIAS
SELECT DATEADD(DAY, -1, GETDATE()); --PEGANDO O DIA DE ONTEM

--DATEPART()
-- ELE INFORMA O ATUAL DIA 
SELECT DATEPART(MONTH, GETDATE());

-- FORMAT 
-- ELE FORMATA A DATA
SELECT FORMAT(CAST(GETDATE() AS DATE),'dd/MM/yyyy');

-- BETWEEN 
-- FAZ VERIFICAÇÃO ENTRE DOIS OU MAIS FATORES 
/*	
	-- ESTÁ SELECIONANDO SOMENTE OS DADOS EM QUE A DATA ESTÁ NO INTERVALO DE 1 ANO ATRÁS DA DATA ATUAL
	SELECT * FROM tabela
	WHERE data BETWEEN DATEADD(YEAR, -1, GETDATE()) AND GETDATE();
*/