-- CRIANDO UMA PROCEDURE 

--STORAGE PROCEDURE P/ POPULAR O BANCO DE DADOS, ESTUDANDO CONCEITOS QUE APRENDI NAS VÍDEO AULAS
CREATE PROCEDURE sp_Popular20
AS
BEGIN
	DECLARE @vCONTADOR INT; 
		SET @vCONTADOR = 0; 

	DECLARE @vALFABETO VARCHAR(26);
		SET @vALFABETO = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

	DECLARE @nALEATORIO INT; 
	DECLARE @vNOME VARCHAR(50);
	DECLARE @vLETRA CHAR; 


	WHILE (@vCONTADOR < 20)
	BEGIN
		SET @vNOME = '';
		WHILE (LEN(@vNOME) <= 3)
		BEGIN
			SET @nALEATORIO = CONVERT(INT, ABS(CHECKSUM(NEWID())) % 26);
			SET @vLETRA = SUBSTRING(@vALFABETO, @nALEATORIO - 1, @nALEATORIO);
			SET @vNOME += @vLETRA;
		END
		INSERT INTO Canal VALUES(@vNOME, @nALEATORIO * 12, GETDATE());
	
		SET @vCONTADOR = @vCONTADOR + 1;

	END
	SELECT * FROM Canal; 
END;

EXEC sp_Popular20;

DROP PROCEDURE sp_Popular20;