USE YoutubeLite

-- TABELAS (Canal, Vídeos)

DECLARE @vSTRING VARCHAR(100); 
	SET @vSTRING = 'SQL                   SERVER          |'; 

/*
DECLARE @vCONTADOR INT; 
	SET @vCONTADOR = 0; 

DECLARE @vNOME VARCHAR(50);

WHILE (@vCONTADOR < 100)
BEGIN 
	SET @vNOME = CONVERT(VARCHAR, @vCONTADOR) + ' - Aba';
	INSERT INTO Canal 
		VALUES (@vNOME, @vCONTADOR * 12, GETDATE()); 

	SET @vCONTADOR = @vCONTADOR + 1;
END
SELECT * FROM Canal;

DELETE FROM canal

*/

-- CÓDIGO PARA POPULAR O BANCO DE DADOS 

DECLARE @vCONTADOR INT; 
	SET @vCONTADOR = 0; 

DECLARE @vNOME VARCHAR(50);

DECLARE @vALFABETO VARCHAR(26);
	SET @vALFABETO = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

DECLARE @nALEATORIO INT; 

SELECT @nALEATORIO

DECLARE @vLETRA CHAR; 

WHILE (@vCONTADOR < 20)
BEGIN
	SET @vNOME = '';
	WHILE (LEN(@vNOME) <= 3)
	BEGIN
		SET @nALEATORIO = CONVERT(INT, ABS(CHECKSUM(NEWID())) % 26);
		SET @vLETRA = SUBSTRING(@vALFABETO, @nALEATORIO - 1, @nALEATORIO);
		SET @vNOME += @vLETRA;
	END
	INSERT INTO Canal VALUES(@vNOME, @vCONTADOR * 12, GETDATE());
	
	SET @vCONTADOR = @vCONTADOR + 1;

END
SELECT * FROM Canal; 







