CREATE DATABASE YoutubeLite
USE YoutubeLite

CREATE TABLE Canal (
	CanalID INT PRIMARY KEY IDENTITY(1,1), 
	Nome VARCHAR(150) NOT NULL, 
	ContagemInscritos INT DEFAULT 0, 
	DataCriacao DATETIME NOT NULL
);

CREATE TABLE Video(
	VideoID INT PRIMARY KEY IDENTITY(1,1), 
	Nome VARCHAR(150) NOT NULL, 
	Vizualizacoes INT DEFAULT 0, 
	Likes INT DEFAULT 0, 
	Dislike INT DEFAULT 0, 
	Duracao INT NOT NULL, 
	CanalID INT FOREIGN KEY REFERENCES Canal(CanalID)
);